hashicorp/packer-plugin-amazon

builder/chroot/builder.go, builder/common/access_config.go, builder/common/access_config_test.go, builder/ebs/builder.go, builder/ebssurrogate/builder.go, builder/ebsvolume/builder.go, builder/instance/builder.go, datasource/ami/data.go, datasource/secretsmanager/data.go, main.go, post-processor/import/post-processor.go, version/version.go
Resolves hashicorp/packer#10315, by adding the plugin version to the User-Agent header sent by the AWS SDK. This is code copied from [session.go in aws-sdk-go-base](https://github.com/hashicorp/aws-sdk-go-base/blob/da4108d88728fcf4f5f9df9ea817285bccf7078e/session.go#L105).
=> Add Packer and packer-plugin-amazon to the User-Agent header

.goreleaser.yml
https://github.com/hashicorp/packer-plugin-amazon/pull/82 breaks the versioning automation and this is the fix.
=> goreleaser - point to the correct version package

builder/common/ami_config.go, builder/common/ami_config_test.go, builder/ebs/builder.go, builder/ebs/builder.hcl2spec.go, builder/ebs/builder_test.go, docs-partials/builder/common/AMIConfig-not-required.mdx, docs-partials/builder/ebs/Config-not-required.mdx
Fix CI failed in 3d9288d, as discussed in this https://github.com/hashicorp/packer-plugin-amazon/pull/99#issuecomment-871600961
=> Moving DeprecationTime field to the config in ebs/builder.go

builder/common/access_config.go
Hi there,
**Description**
Packer handles [debug flag](https://www.packer.io/docs/debugging) that should help developers to figure out where is the problem.
By some reason we don't propagate this flag to [awsbase.Config](https://github.com/hashicorp/packer-plugin-amazon/blob/main/builder/common/access_config.go#L343)`. It could hides some important logs.
**Story**
For example, today I had a problem I tried to assume a role with pretty small duration time(60 seconds), but AWS [doesn't support](https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html#options) so small value(min value is 900 seconds) and raises an exception in this case like this:
```
Role (arn:aws:iam::ACCOUNT:ROLE) cannot be assumed.
There are a number of possible causes of this - the most common are:
* The …
```
=> enable aws debug logs

builder/common/artifact.go, builder/common/artifact_test.go, builder/ebsvolume/artifact.go, builder/ebsvolume/artifact_test.go, go.mod, go.sum
Adds SourceAMI to the PARtifact, so that hcp packer registry can track image ancestry.
=> add SourceAMI to PARtifact

builder/common/run_config.go, builder/common/step_get_password.go, builder/common/step_key_pair.go, builder/common/step_security_group.go, builder/common/step_stop_ebs_instance.go, builder/common/tags.go, builder/ebs/builder.go, builder/ebs/step_create_ami.go, builder/ebssurrogate/builder.go, builder/ebsvolume/builder.go, builder/instance/builder.go, docs-partials/builder/common/RunConfig-not-required.mdx, go.sum, post-processor/import/post-processor.go
The EC2 service allows for most resources to be tagged on creation. This, together with the [CreateAction IAM Condition](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/supported-iam-actions-tagging.html), allows us to restrict Packer to manage only the resources it creates.
This PR adds [TagSpecification](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_TagSpecification.html)s to the following resources using the `run_tags` variable.
- Key-pairs
- Security Groups
- EBS based Instances
- EBS based AMIs
- EBS based Snapshots
The `run_tags` variable was chosen to avoid clutter in the `source` block but as the tags are now attached to both the AMI and snapshot after Packer has finished running one could argue that they should be moved to their own variable.
The tags added on …
=> add tag specification to resources to enable security tagging

builder/ebs/builder.go
This PR changes the order that PackerConfig is constructed for the Runner.
It moves  `stepEnableDeprecation` after the AMI is created, this allows the Deprecation Time to be successfully applied to AMIs when copying to multiple regions.
An example configuration is in the issue 
Closes #137
=> Fix `deprecate_at` when copying to additional regions

builder/chroot/builder.go, builder/ebssurrogate/builder.go, docs-partials/builder/chroot/Config-not-required.mdx, docs-partials/builder/ebssurrogate/Config-not-required.mdx
Add support for i386 and x86_64_mac architectures to `amazon-chroot` and `amazon-ebssurrogate` builders.
Closes #153
=> add missing i386 and x86_64_mac architectures

builder/common/ami_config.go, builder/common/ami_config_test.go
CHANGELOG
```
Fix invalid KMS key error for multi-region keys containing no dashes.
```
Turns out multi-region keys have ids prefixed with mrk- followed by
hexadecimal values with or without dashes. This change updates the
previously suggested regex to account for known variations of
multi-region kms keys.
Closes #125 
Related to #147
=> Update validation for multi-region keys

builder/chroot/builder.go, builder/chroot/builder.hcl2spec.go, builder/chroot/step_register_ami.go, builder/ebssurrogate/builder.go, builder/ebssurrogate/builder.hcl2spec.go, builder/ebssurrogate/step_register_ami.go, docs-partials/builder/chroot/Config-not-required.mdx, docs-partials/builder/ebssurrogate/Config-not-required.mdx
This enables passing an option `boot_mode` in the configurations for chroot and
ebssurrogate builders. This enables booting in `uefi` mode in addition to
`legacy-bios`.
The option is added only to the chroot and ebssurrogate builders because:
* The ebs builder uses the `CreateImage` API call, which inherits the boot mode
from the source instance.
* The instance builder uses Amazon's AMI Tools, and per the EC2 user guide for
creating instance store images, the command `ec2-bundle-vol` from AMI Tools
does not bundle the /boot/efi directory if present, so it seems to be
unsupported.
* The ebsvolume builder does not create an image so it is not needed.
If `boot_mode` is not defined in the configuration, the builders do not pass
a value for it to AWS, rather it is left unset so the default …
=> Add a boot mode option to builders

builder/common/run_config.go, builder/common/run_config.hcl2spec.go, builder/common/step_run_source_instance.go, builder/ebs/builder.go, builder/ebs/builder.hcl2spec.go, builder/ebssurrogate/builder.go, builder/ebssurrogate/builder.hcl2spec.go, builder/ebsvolume/builder.go, builder/ebsvolume/builder.hcl2spec.go, builder/instance/builder.go, builder/instance/builder.hcl2spec.go, datasource/secretsmanager/data.go, docs-partials/builder/common/LicenseConfigurationRequest-not-required.mdx, docs-partials/builder/common/LicenseSpecification-not-required.mdx, docs-partials/builder/common/Placement-not-required.mdx, docs-partials/builder/common/RunConfig-not-required.mdx
This PR adds support for scheduling instances to [host resource groups](https://docs.aws.amazon.com/license-manager/latest/userguide/host-resource-groups.html), which likewise requires the declaration of a [license configuration](https://docs.aws.amazon.com/license-manager/latest/userguide/license-configurations.html).
While the AWS SDK allows for a collection of license configurations, this PR flattens that to one in accordance with some of the other conventions observed. I'm open to changing that decision, updating the data model to more accurately reflect the collection of license configurations that comprise a license specification.
In all honesty I would prefer to group the `tenancy` and `host_resource_group_arn` settings under a `placement` grouping, but I wasn't sure what the …
=> add license-specifications and placement/host-resource-group-arn

docs/post-processors/import.mdx, post-processor/import/post-processor.go, post-processor/import/post-processor.hcl2spec.go
This PR allows creation of [UEFI based](https://aws.amazon.com/about-aws/whats-new/2021/03/amazon-ec2-now-supports-uefi-boot-when-migrating-virtual-machines-to-ec2/) amis as well arm64/graviton based AMIs
=> Import post processor: Allow creation of AMIs with uefi boot & graviton support 

builder/common/run_config.go, docs-partials/builder/common/RunConfig-not-required.mdx
Hi, this updates the documentation for the parameter (ebs#block_duration_minutes) so everyone is aware of the it's deprecation to new customers.
Please do suggest changes to the way it's phrased if you think it can be improved.
Closes #176
=> Docs update: add note for block_duration_minutes

builder/chroot/builder.go, builder/common/build_filter.go, builder/common/build_filter_test.go, docs-partials/builder/chroot/Config-not-required.mdx
Currently, EC2 filter values are treated as a single string item. However, to the AWS API, they are lists of strings. `buildEc2Filters` creates the struct expected by the API, but does not handle the case where the user wants to pass several values for the filter option.
This patch parses the filter option values as csv strings, to maintain backwards compatibility with the current interface while allowing users to pass a multi-valued argument.
Closes #13
=> Parses filter option values as csv strings

builder/common/step_key_pair.go, builder/common/step_key_pair_test.go, builder/ebs/builder.go, builder/ebs/builder_acc_test.go, builder/ebs/test-fixtures/rsa_ssh_keypair.pkr.hcl, builder/ebssurrogate/builder.go, builder/ebsvolume/builder.go, builder/instance/builder.go
After reviewing https://github.com/hashicorp/packer-plugin-amazon/pull/179 with Wilken we came to the conclusion that we should add a unit test to the KeyPair step so that the aforementioned PR can be tested (just need to remove comments in step_key_pair_test)
I ended up having to make a small change to each builder to put the region in the state before the steps are run, previously step_key_pair would access Region through the ec2 object (ec2conn.Config.Region), since we now cast that as an ec2iface to be able to mock it in the test, we are no longer able to access the Config object within the step, since the interface does not know about the Config object (might be an upstream fix there)
=> Add Unit test for KeyPair step

builder/chroot/builder.go, builder/common/ami_filter.go, builder/common/build_filter.go, builder/common/build_filter_test.go, builder/common/run_config.go, builder/common/step_network_info.go, builder/common/step_security_group.go, docs-partials/builder/chroot/Config-not-required.mdx, docs-partials/builder/common/RunConfig-not-required.mdx
After https://github.com/hashicorp/packer-plugin-amazon/pull/174 @azr pointed out that we should bubble up errors from csv parsing, this PR bubbles up that error, and addresses some other docs feedback.
For testing I added checks that errors aren't thrown to both existing filtering unit tests, I felt like adding additional tests wasn't worth it for this error, we can decide to refactor the build filter class to accept a mocked csv parser if folks want to though.
Addresses feedback from: https://github.com/hashicorp/packer-plugin-amazon/pull/174#discussion_r790534015 and https://github.com/hashicorp/packer-plugin-amazon/pull/174#discussion_r790903152
=> Change error handling with CSV Parsing of filters

builder/common/ami_config.go, builder/common/step_run_source_instance.go, builder/common/step_run_spot_instance.go, docs-partials/builder/common/AMIConfig-not-required.mdx
This fixes #155 and a is breaking change.
We should probably bump the minor version for the next release.
=> Remove default tagging

builder/common/ami_config.go, docs-partials/builder/common/AMIConfig-not-required.mdx
in https://github.com/hashicorp/packer/commit/b20e26be17b56e893d9b29945441041824d0e110 a limit for the ami_groups was added but that is not in this documentation anymore, even though the official docs suggest this is still the only value possible: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_LaunchPermission.html
=> docs: specify valid values for ami_groups

builder/common/step_run_source_instance.go
Fix build failure when no source instance tags are present in restricted
regions.
e83d836e removed default tagging for source instances which introduces
the potential for launching an instance with an empty ec2Tags list.
This was handled for regions that support tagging on instance creation
but not in restricted regions (GovCloud and China) where tags are
applied to the instance after creation.
=> Handle empty source tags in restricted regions

builder/ebs/builder.go, builder/ebssurrogate/builder.go, builder/ebsvolume/builder.go, builder/instance/builder.go
Tag-On Create for EC2 and EBS is now supported on GovCloud:
https://aws.amazon.com/about-aws/whats-new/2018/07/tag-on-create-for-amazon-ec2-and-amazon-ebs-is-now-available-in-the-aws-govcloud-region/
isRestrcted is only used to gate Tag-On Create and is no longer needed
for GovCloud.
=> Remove GovCloud from isRestricted run source param

builder/ebs/builder.go, builder/ebs/step_enable_deprecation.go
When a build file specifies a deprecation time on an AMI, and includes
the skip_create_ami directive in the configuration, the AMI map ends up
not being created in the state for the build, causing the depreciation
step to panic on an interface conversion.
This commit avoids such a problem by checking if the AMI map is indeed a
map and not nil before proceeding.
If it is not the expected type, we stop the build.
Closes #224
=> ebs/ami_deprecation: don't crash when AMIs are nil

builder/common/build_filter.go, builder/common/build_filter_test.go
Currently, if a filter has quotes in the value, it fails with:
```
Build 'amazon-ebs.ebs' errored after 1 second 208 milliseconds: Couldn't parse subnet filters: parse error on line 1, column 2: bare " in non-quoted-field
```
I believe this is because https://github.com/hashicorp/packer-plugin-amazon/pull/174. This adds a test to confirm and then enables `LazyQuotes` which I got the idea from https://stackoverflow.com/questions/31326659/golang-csv-error-bare-in-non-quoted-field. The test now passes.  
Closes https://github.com/hashicorp/packer-plugin-amazon/issues/226
=> Enable csv LazyQuotes in build_filter

builder/common/step_run_spot_instance.go
With the removal of the default Packer Builder tag in #191 the default
set of tags for a source instance is empty, which throws an error when trying to
create a tag input with an empty set. This error will not occur if the
run_tags attribute is provided. But since Packer was injecting a default
tag this issue never manifested itself.
Closes #223
=> Update spot instance run to handle empty tags set

builder/common/run_config.go, builder/common/step_run_source_instance.go, builder/common/step_run_spot_instance.go, builder/common/step_run_spot_instance_test.go, docs-partials/builder/common/MetadataOptions-not-required.mdx
The ability to include instance tags within the instance metadata
service is not supported for non-commercial regions such as GovCloud.
This change will only include the configuration for instances metadata
tags when enabled. By default, where supported, unspecified settings
will use the default API value of "disabled". Enabling support for tags
in a unsupported region will result in an AWS launch error, which will
terminate the build.
Closes #242
=> Remove tags from InstanceMetadataOptionsRequest when in the default state to fix launch issue for unsupported regions

.gitignore, builder/common/run_config.go, builder/common/step_run_source_instance.go, builder/common/step_run_spot_instance.go, builder/common/step_run_spot_instance_test.go, docs-partials/builder/common/RunConfig-not-required.mdx
Change AssociatePublicIpAddress to a bool pointer, making it a tristate variable as it's already defined on HCL. 
This enables to explicitly set a `NetworkInterface` with `AssociatePublicIpAddress` set to false.
We tested the built plugin on our AWS account with the SCP rule mentioned on #240, it works perfectly. 
Closes #240
=> Change AssociatePublicIpAddress to a bool pointer

builder/ebs/builder.go, builder/ebs/builder_acc_test.go
This PR fixes #249.
Looking at the general order of steps in `ebs/builder.go`, I noticed that enabling deprecation was done _before_ copying the AMI to other regions and/or encrypting said AMI's. Since EC2's `CopyImage` request does not copy the deprecation attribute, these steps should be switched.
It also seems to make more sense, since `StepModifyAMIAttributes` and `StepCreateTags` were also executed _after_ the Region Copy step.
=> [bugfix] Allow Enable-Deprecation on copied or encrypted AMIs

builder/common/run_config.go, builder/common/run_config_test.go, builder/common/step_run_source_instance.go, builder/ebs/builder.go, builder/ebs/builder.hcl2spec.go, builder/ebssurrogate/builder.go, builder/ebssurrogate/builder.hcl2spec.go, builder/ebsvolume/builder.go, builder/ebsvolume/builder.hcl2spec.go, builder/instance/builder.go, builder/instance/builder.hcl2spec.go, docs-partials/builder/common/RunConfig-not-required.mdx
Adds support for enabling Nitro Enclaves on instance.  An example config would be: 
```
source "amazon-ebs" "example" {
enable_nitro_enclave = true
}
```
Closes #245
=> Add `enable_nitro_enclave` argument to enable support for Nitro Enclaves on instance

version/version.go
Release version 1.1.4 of the Amazon plugin
=> version: cut version for 1.1.4

builder/common/run_config.go, builder/common/run_config_test.go, builder/common/step_run_source_instance.go, builder/common/step_run_spot_instance.go, builder/ebs/builder.go, builder/ebs/builder.hcl2spec.go, builder/ebs/builder_acc_test.go, builder/ebs/test-fixtures/unlimited-credits/burstable_instances.pkr.hcl, builder/ebs/test-fixtures/unlimited-credits/burstable_spot_instances.pkr.hcl, builder/ebssurrogate/builder.go, builder/ebssurrogate/builder.hcl2spec.go, builder/ebsvolume/builder.go, builder/ebsvolume/builder.hcl2spec.go, builder/instance/builder.go, builder/instance/builder.hcl2spec.go, docs-partials/builder/common/RunConfig-not-required.mdx
- Add support to toggle unlimited credits for t3 and t4g instance types.
- Add deprecation warning for EnableT2Unlimited to all builders
- Add test validating EnableUnlimitedCredits is true when EnableT2Unlimited is true
- Update default credit type to standard for all burstable instance types
- Add EnableUnlimitedCredits for spot instance type builds
- Update StepRunSourceInstance to use CPUCredits const values
- Add acceptance test for enable_unlimited_credits
Closes #127
=> Add support for toggling unlimited credits for T3/T3a/T4g instance type

builder/chroot/builder.go, builder/chroot/builder.hcl2spec.go, builder/chroot/builder_test.go, builder/chroot/step_register_ami.go, builder/ebssurrogate/builder.go, builder/ebssurrogate/builder.hcl2spec.go, builder/ebssurrogate/builder_acc_test.go, builder/ebssurrogate/builder_test.go, builder/ebssurrogate/step_register_ami.go, builder/instance/builder.go, builder/instance/builder.hcl2spec.go, builder/instance/builder_test.go, builder/instance/step_register_ami.go, docs-partials/builder/chroot/Config-not-required.mdx, docs-partials/builder/ebssurrogate/Config-not-required.mdx, docs-partials/builder/instance/Config-not-required.mdx, go.mod, go.sum
Add support for enabling IMDSv2 by default by using the new `imds_support` configuration option.
Closes #277 
---
Open issues/items:
=> Add support for configurating IMDSv2 as the default instance metadata service

builder/chroot/builder.go, builder/chroot/builder.hcl2spec.go, builder/chroot/builder_test.go, builder/chroot/step_register_ami.go, builder/ebssurrogate/builder.go, builder/ebssurrogate/builder.hcl2spec.go, builder/ebssurrogate/builder_test.go, builder/ebssurrogate/step_register_ami.go, docs-partials/builder/chroot/Config-not-required.mdx, docs-partials/builder/ebssurrogate/Config-not-required.mdx
Add support for `uefi_data` to register an AMI with a pre-populated UEFI variable store.
This is necessary for Secure Boot and to use custom UEFI boot entries.
Such variable stores can be created with https://github.com/awslabs/python-uefivars, by using the `aws` format the base64 encoded variable store can be passed to `uefi_data`.
Available for chroot and ebssurrogate builders which use `RegisterImage` and support `boot_mode`.
Closes #253
=> Add support for `uefi_data` in builders

builder/common/state.go, builder/common/step_run_source_instance.go, builder/common/step_run_spot_instance.go, builder/common/step_run_spot_instance_test.go
When launching ec2 source instances, we have code which waits for the instance to become ready, but previously this codepath was not being applied to spot instances.
This change factors that code out into a common function, and then calls that common function in both the 'regular' and 'spot' instance launches.
This fixes issues where packer tries to connect to a spot instance before it is running and ready, which means it won't have a public ip address ready yet, and so packer times out on SSH access.
fixes #40
=> Fix spot instance launch readiness

builder/common/step_create_ssm_tunnel.go, builder/ebs/acceptance/utils.go, builder/ebs/builder.go, builder/ebs/builder_acc_test.go, builder/ebssurrogate/builder.go, builder/ebssurrogate/builder_acc_test.go, builder/ebsvolume/builder.go, builder/instance/builder.go
Improves SSM session manager feature by disabling key pair creation when user specifies a private key pair to be used.
The current implementation works fine for cases where the user does not specify a private key to be used with `session_manager`. In cases where the user specifies a private key, then that key will be used to authenticate but it fails since the key is not present on the EC2 instance.
This PR will resolve the issue by [sending the user public key](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2instanceconnect/#EC2InstanceConnect.SendSSHPublicKey) to the instance before connecting to it.
If the user does not specify a private key, then works like the previous implementations.
In the case where the user specifies a private key to be used:
1. key pair will not be …
=> session_manager: Upload user public key to instance before connection if private key is specified

builder/common/ssh.go
Previously the ssh access IP would fallback to the private ip address on the first "try" if a public IP is not available yet.
This changes the logic to only fallback to private IP address if we are on the final attempt at finding an IP address.
Precedence of always preferring public IP is left unchanged.
related to #40 and #308
=> Instance SSH access: use all attempts to get public IP

builder/ebs/acceptance/utils.go
Some acceptance tests require generating a temporary SSH key pair for ensuring they are sent to AWS and that we can connect through SSH to an instance with a user-provided key.
This was implemented through `ssh-keygen', part of the openssh suite of tools, but because the behaviour may change between environments, we opted to rewrite the keygen steps in pure go, by relying on the functions exposed by the `crypto' standard library.
=> acceptance: use pure Go for generating temp keys

builder/common/step_create_ssm_tunnel.go, builder/ebs/builder_acc_test.go
Skip uploading SSH public key to the instance in case the AWS key pair is used.
In case key pair is generated and it's not specified by the user uploading the key is not necessary.
Since this issue can be identified with the roles running packer itself, I'm unsure if I can reflect this change in tests. Any help is appreciated. I tested it on my local machine with two configs:
- With SSM and no privateKeyFile: Does not upload the pub key
- With SSM and with privateKeyFile: Uploads the pub key
Closes #313
=> Skip uploading ssh pub key when AWS key pair is used

builder/ebs/builder_acc_test.go
The acceptance test that would generate an SSH key prior to running it was failing on Windows machines in CI as it made the process timeout.
While this is not clear why that happens, we fixed the issue earlier by adding this extra check prior to running the test, so it is not run when running normal tests in CI.
Because we now generate this SSH key directly from Go code, and not by relying on ssh-keygen, we can remove this as we don't risk encountering this problem anymore.
In addition, the EBS test in which we push the public key corresponding to the private key we add in the configuration on an SSM-backed connection would not check that the SSH public key upload message was in the output, potentially leading to some inconsistencies in the future.
To avoid this from happening at some …
=> Harden EBS ssh key tests

builder/common/ssm/session.go, builder/common/step_create_ssm_tunnel.go, builder/ebs/builder_acc_test.go
With the current implementation was failing in case of a restart in execution commands
With the current implementation was failing in case of a restart in execution commands, for example:
```hcl
build {
sources = ["source.amazon-ebs.test"]
provisioner "shell" {
expect_disconnect = true
script            = "./reboot.sh"
}
provisioner "shell" {
inline = ["echo 'Hello World!'", "echo >>/home/ec2-user/test-inline.txt"]
}
}
```
Would not continue after the first script is ran.
To fix this I have changed the code to monitor the instance connection status to SSM service, and in case the session is disconnected it will re-create another session to SMS. This session will be kept open(in case of future crashes) until the packer actually stops the instance.
A few important details:
**How do we …
=> Handle SSM session disconnection w/ AWS get connection status.

builder/common/run_config.go, builder/common/step_iam_instance_profile.go, builder/common/tags.go, builder/ebs/builder.go
RunTags value is used to set tags for resources created by packer except for Iam role and profile. This PR adds the tags when creating these resources.
Resolves #322
This will also address part of #286
=> iam: attach tags to instance role and profile

builder/common/run_config.go, builder/common/step_run_source_instance.go, builder/common/step_run_spot_instance.go
This PR adds run_tags to ec2 instance network interfaces.
From the [RunInstanceInput](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#RunInstancesInput) we can see that the NetworkInterface tags are also applied from the TagSpecification field.
To test the code block in the IsRestricted, I manually turned it on and built an AMI.
Closes #286
=> Add run_tags to ec2 instance network interfaces

builder/common/block_device.go
Clarifying the reason for error message saying throughput is unavailable.
While building an Ubuntu AMI using [kubernetes-sigs/image-builder](https://github.com/kubernetes-sigs/image-builder), which uses Packer (and packer-plugin-amazon) under the hood, I got the following error:
```bash
Error: Failed to prepare build: “ubuntu-20.04”
1 error(s) occurred:
* Throughput is not available for device /dev/sda1
```
I had set my volume type to `gp2` and did not set throughput, but what I didn't know at the time was that image-builder has a default throughput value of `125` set [here](https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/packer/ami/packer.json#L204), which was causing the volume type/throughput incompatibility. I am aware now that the docs mention the throughput …
=> Clarify reason for invalid throughput error message

builder/chroot/builder.go, builder/chroot/builder.hcl2spec.go, builder/chroot/step_register_ami.go, builder/common/ami_config.go, builder/common/step_modify_ami_attributes.go, builder/ebs/builder.go, builder/ebs/builder.hcl2spec.go, builder/ebs/builder_acc_test.go, builder/ebs/builder_test.go, builder/ebssurrogate/builder.go, builder/ebssurrogate/builder.hcl2spec.go, builder/ebssurrogate/step_register_ami.go, builder/instance/builder.go, builder/instance/builder.hcl2spec.go, builder/instance/step_register_ami.go, docs-partials/builder/chroot/Config-not-required.mdx, docs-partials/builder/common/AMIConfig-not-required.mdx, docs-partials/builder/common/AWSPollingConfig.mdx, docs-partials/builder/ebssurrogate/Config-not-required.mdx, docs-partials/builder/instance/Config-not-required.mdx, go.mod, go.sum
Recently AWS started supporting setting the ImdsSupport attribute on all AMIs after their creation, and not only when registering it.
We leverage this change in this PR to enable the `imds_support` attribute on all builders that create AMIs, including EBS.
Closes #310
=> Imds support ebs

builder/chroot/builder.go, builder/common/boot_mode_validation.go, builder/common/boot_mode_validation_test.go, builder/ebssurrogate/builder.go, post-processor/import/post-processor.go
This PR refactors the boot check validation so all entities can use the same code to validate their option's value, and adds support for the `uefi-preferred` value.
Closes #340
=> Uefi preferred boot mode check

builder/common/step_ami_region_copy.go, builder/common/step_ami_region_copy_test.go, builder/ebs/builder_acc_test.go
As pointed out in #295, the tags specified as `run_tags` in a template are applied to the resulting base AMI, but are not copied to the AMIs that are copied from it to other regions.
This does not apply to tags specified through the `tags` attribute since they are manually copied through an extra step, after the AMIs are created and copied.
To fix the first use case, Amazon added support for copying the tags when an AMI is copied to another region, so we leverage that in this PR.
Closes #295
=> Copy tags on copy ami

.github/actions/build-and-persist-plugin-binary/action.yml, .github/workflows/build_plugin_binaries.yml
Running the actions to upload binaries fails with a pathing issue since relative pathing is unsupported for the upload-artifact action.
=> github: fix pathing issues for building binaries

builder/common/ami_config.go, builder/common/ami_config_test.go
Closes: #356
```
~>  make test
?   	github.com/hashicorp/packer-plugin-amazon	[no test files]
ok  	github.com/hashicorp/packer-plugin-amazon/builder/chroot	7.391s
ok  	github.com/hashicorp/packer-plugin-amazon/builder/common	11.286s
?   	github.com/hashicorp/packer-plugin-amazon/builder/common/awserrors	[no test files]
?   	github.com/hashicorp/packer-plugin-amazon/builder/common/ssm	[no test files]
ok  	github.com/hashicorp/packer-plugin-amazon/builder/ebs	13.355s
?   	github.com/hashicorp/packer-plugin-amazon/builder/ebs/acceptance	[no test files]
ok  	github.com/hashicorp/packer-plugin-amazon/builder/ebssurrogate	11.938s
ok  	github.com/hashicorp/packer-plugin-amazon/builder/ebsvolume	11.874s
ok  	github.com/hashicorp/packer-plugin-amazon/builder/instance	9.491s
ok …
```
=> Add support for KMS keys in the aws-cn partition

builder/common/step_network_info.go, builder/ebs/builder_acc_test.go
In version 1.2.3 of the AWS plugin, we changed the way we set the subnet when the associate_public_ip_address argument is not unset.
This had the side-effect of breaking configuration which specified a subnet_id or a subnet_filter, as it would always default on inferring the most available one from the default (or selected) VPC.
This was a bug, and is fixed with this commit.
Closes #367
Related to #368
=> common: fix subnet_filters when public IP set

builder/common/step_pre_validate.go
I maintain the [EKS-optimized AMI](https://github.com/awslabs/amazon-eks-ami), and as a result I build a lot of AMI's. 😄 
Our current naming convention for AMI's uses a date of the form `YYYYMMDD`. For better or worse, that's what we do. We have internal processes that build AMI's using this naming convention, and subsequently grant permissions for those AMI's to various other AWS accounts.
The pre-validate step in the `amazon-ebs` builder will fail if any existing AMI returned by a `ec2.DescribeImages` call uses the proposed name. This makes sense, because the later `ec2.CreateImage` call will fail with a `InvalidAMIName.Duplicate` code if there is such a collision, after we've already executed the time-consuming steps.
But, this `ec2.CreateImage` error only occurs when the *caller* has …
=> Include only AMI's owned by caller during pre-validate

builder/common/run_config.go, builder/common/step_network_info.go, builder/common/step_network_info_test.go, builder/ebs/builder.go, builder/ebs/builder_acc_test.go, builder/ebssurrogate/builder.go, builder/ebsvolume/builder.go, builder/instance/builder.go
This PR is an attempt to fix the problem where we pick a subnet that cannot spawn an instance of the type requested as the AZ linked to the subnet does not support it.
We also add some basic unit-tests for the step, which will be improved upon in upcoming PRs.
Related to #368 
Related to #371
=> Select subnet based on az machine type availability

builder/ebs/builder.go, docs-partials/builder/common/RunConfig-not-required.mdx, docs-partials/builder/ebs/Config-not-required.mdx, docs/builders/ebs.mdx
The fast-launch configuration block was added a couple of versions ago, but its documentation was never added to the docs page for the plugin.
This PR fixes that problem.
=> Fix docs for fast launch

docs/builders/index.mdx
Since the `associate_public_ip_address' attribute may need to use the `DescribeVpcs' permission in order to get the default VPC information, we add this explanation to the IAM section in the docs.
=> docs: add public ip paragraph in IAM section

.github/workflows/acceptance-tests.yml
Since right now we don't have any way to run acceptance tests on the AWS plugin, we add a workflow that can manually be triggered.
=> .github: add action to run acceptance tests

.github/workflows/acceptance-tests.yml
When running the action to run the acceptance tests, the step to install the AWS cli fails since there's already a version installed.
To prevent this from making the action fail, we invoke the installation script with the `--update' flag, so it will override the current version with the latest from Amazon.
=> workflows: run awscli install with update flag

.github/workflows/acceptance-tests.yml
Since the Github runner already has the AWS cli and the session-manager plugin installed, there's no point in installing it ourselves, so we remove the script that does that for this workflow.
=> workflows: remove AWS cli install from acc tests

.github/workflows/acceptance-tests.yml
The action to get temporary credentials for AWS was referring to secrets under `env', which resulted in the arguments for the action being empty, and therefore failing.
=> workflows: reference secrets not as env vars

.github/workflows/acceptance-tests.yml
When the acceptance tests fail for any reason, the logs of the failed run is kept as a text file in the builder's directory. Having access to those is important to diagnose what went wrong during the test run, so we add some extra steps to the job that runs them in order to compress and export them as artifact for the run.
=> workflows: zip and keep logs for acceptance tests

docs/builders/index.mdx
While running acceptance tests on an account/role with the permission set specified in our docs, we had some failures because of missing permissions.
This commit adds some docs on those missing permissions when attempting to build AMIs with specific options turned on.
=> docs: add more permissions troubleshooting details

.github/workflows/acceptance-tests.yml
This PR adds a schedule to run acceptance tests every Sunday at 4:00 AM (UTC), and adds a job to run acceptance tests on the `ebssurrogate` builder as well.
=> Acc tests schedule

.github/workflows/acceptance-tests.yml
Last run failed after ~3h runtime, which is dangerously close to the timeout previously set. While the logs don't show stack traces, it's possible they did timeout, so to highten their chances to finish the acutal tests, we bump the timeout to 5h, and raise the session duration for the token to 6h.
=> github: bump timeout duration for acceptance tests

docs/builders/index.mdx
There was an error for in the Visual Policy Editor when I copy/pasted the JSON and then went to view it, picture below.
So, I found that it was a capitalization error with that permission, so I changed `ec2:CreateKeypair` to `ec2:CreateKeyPair`. (capital `p` in the `Pair` part of the word)
=> fixing text for IAM permission needed

builder/common/step_pre_validate.go, builder/ebs/builder.go
Pretty simple fix that just adds a conditional to the **step_pre_validate** to skip it in case the skip_create_ami flag is set to true. I kept the look and format consistent with the existing skips that were already present.
Closes #409
=> ebs: skip_create_ami skips prevalidation of AMI name (#409)

go.mod, go.sum
Upgrading `aws-sdk-go` to fix the issue with usage with SSO.
Tested with the following configuration:
```ini
[profile dummy]
sso_session = dummy
sso_account_id = REDACTED
sso_role_name = dummy-role
region = us-east-1
output = json
[sso-session dummy]
sso_start_url = https://d-REDACTED.awsapps.com/start#
sso_region = us-east-1
sso_registration_scopes = sso:account:access
```
Closes #350
=> feat: upgrade aws-sdk-go to fix SSO issue

builder/ebs/builder_acc_test.go
Testing for the AMI sharing between accounts requires multiple extra variables to be set so we can interpolate those values in the template we run the test on.
In case it is not set, the current setup makes acceptance tests fail, which can be counter-productive.
To avoid this problem, we don't error when these variables are not set, but instead we skip the test.
=> ebs: don't error on AMI sharing test unset

.web-docs/components/data-source/ami/README.md, builder/common/ami_filter.go, builder/common/run_config.hcl2spec.go, builder/common/step_source_ami_info.go, datasource/ami/data.hcl2spec.go, docs-partials/builder/common/AmiFilterOptions-not-required.mdx
When getting the AMIs to build a new image on, we never included deprecated AMIs, as is the default when describing images on AWS.
However, the request does offer this option, so we add this to the options to pick from when getting the base AMI.
Closes #403
=> common: add include_deprecated option to filters

builder/common/run_config.go, builder/common/run_config.hcl2spec.go, builder/common/run_config_test.go, builder/common/step_run_source_instance.go, builder/ebs/builder.go, docs-partials/builder/common/Placement-not-required.mdx
This PR adds support for specifying an exact dedicated host ID in the placement block. We were originally running this when `mac2.metal` instances weren't publicly available and AWS API behaviour around them was weird enough that Packer couldn't see them in responses that didn't query a specific ID.
This addresses a specific issue we experience - since by default, the source will grab whatever the first available host is, we occasionally find ourselves with the problem of Packer "stealing" from the wrong pool because for various lifecycle reasons, another host was available. With this change, an end user can instead provide a specific host ID (e.g. via a variable, from the response of an external call to the AWS API creating a new dedicated host resource), ensuring that the correct host …
=> builder: allow specifying hostId for placement

.github/workflows/acceptance-tests.yml, builder/ebs/builder_acc_test.go, builder/ebs/test-fixtures/interpolated_run_tags.json, builder/ebs/test-fixtures/interpolated_run_tags.pkr.hcl, builder/ebs/test-fixtures/ssh-keys/ed25519_ssh_keypair.pkr.hcl, builder/ebs/test-fixtures/ssh-keys/rsa_ssh_keypair.pkr.hcl, datasource/ami/test-fixtures/template.pkr.hcl
This change updates the Ubuntu image in the Linux acceptance test to a non-deprecated Jammy 22.04 server. This change fixes the failing acceptance tests.
=> Replace Xenial with Jammy image

.web-docs/components/builder/ebs/README.md, docs/builders/ebs.mdx, example/build.pkr.hcl, example/instance-metadata/ubuntu-imdsv2-enabled.json, example/instance-metadata/ubuntu-imdsv2-enabled.pkr.hcl
- Add working example for enabling metadata service v2
- Update basic build to use non-deprecated ami
- Add documentation for enabling instance metadata v2
Closes #357
=> docs: Add working example for enabling metadata service v2

.web-docs/components/post-processor/import/README.md, docs/post-processors/import.mdx, post-processor/import/post-processor.go, post-processor/import/post-processor.hcl2spec.go
Setting platform for the image-import task fixes a bug where the process gets stuck as mentioned in #433 
If your PR resolves any open issue(s), please indicate them like this so they will be closed when your PR is merged:
Closes #433
=> feat: add platform flag for ec2 image import task

.web-docs/components/builder/chroot/README.md, .web-docs/components/builder/ebs/README.md, .web-docs/components/builder/ebssurrogate/README.md, .web-docs/components/builder/instance/README.md, builder/common/ami_config.go, docs-partials/builder/common/AMIConfig-not-required.mdx
As pointed out by a user on discuss, the region_kms_key_ids attribute was not referenced correctly in the documentation for kms_key_id.
This commit fixes this mistake, along with a typo in the documentation for `kms_key_id'.
=> common: doc fixes for kms regions

builder/ebs/builder_acc_test.go, builder/ebs/step_enable_fast_launch.go
Following up on issue #445, this PR adds more diagnostics to the step that enables fast-launch.
Since the wait step only waited for the state to change to either "enabled", "enabled-failed" or "enabling-failed", but later on the code didn't check the state was indeed "enabled", we could end-up in a situation where the fast-launch step failed on AWS, but the plugin would count it as a success.
Note: I couldn't replicate such a scenario in my tests, but this remains a possibility, so I hope the community will someday share a template that we can adapt to ensure the plugin does take this into account.
Also, added some checks to signal the step is being skipped if no AMI's present in the plugin's state bag, as otherwise the step would silently succeed without doing anything.
Finally, we also …
=> Add more diags on fast-launch enable step

.web-docs/components/builder/ebs/README.md, builder/ebs/builder.go, builder/ebs/builder_acc_test.go, builder/ebs/builder_test.go, builder/ebs/fast_launch_setup.go, builder/ebs/fast_launch_setup.hcl2spec.go, builder/ebs/fast_launch_setup_test.go, builder/ebs/step_enable_fast_launch.go, builder/ebs/step_prepare_fast_launch_template.go, docs-partials/builder/ebs/FastLaunchConfig-not-required.mdx
Prior to this commit, enabling fast-launch was done before copying the AMI to other regions, if the option was selected.
This was problematic, as the pre-provisioned snapshots produced by enabling fast-launch weren't copied over to other regions, so only the source image was supporting fast-launch.
To remedy this problem, we now enable fast-launch after the image is copies to other regions. This fixes the problem, but takes more time to complete the build, since each enabling takes time.
Also, this requirement means that each region may have its own launch template to use for enabling fast-launch, so we introduce a new block in the configuration to specify which region should use which template.
This option does not directly supersede the original `fast_launch_template*` options, but …
=> ebs: add fast-launch support with AMI copies

.web-docs/components/builder/ebs/README.md, builder/ebs/fast_launch_setup.go, builder/ebs/fast_launch_setup.hcl2spec.go, docs-partials/builder/ebs/FastLaunchConfig-not-required.mdx, docs-partials/builder/ebs/FastLaunchTemplateConfig-not-required.mdx, docs-partials/builder/ebs/FastLaunchTemplateConfig.mdx, docs/builders/ebs.mdx
Introduced with v1.3.0 of the plugin, the fast-launch-template-config was not added to the docs, and since the partials were generated, but not committed, the release docs deployment failed.
This likely hints at the checks for the PR not being sufficient, as they should have pointed it out, but that wasn't the case.
Follow-up to: #451
=> docs: fix fast-launch-template-config docs

.web-docs/components/builder/ebsvolume/README.md, builder/ebsvolume/block_device.go, builder/ebsvolume/builder.go, builder/ebsvolume/builder.hcl2spec.go, builder/ebsvolume/step_snapshot_ebs_volumes.go, docs-partials/builder/ebsvolume/BlockDevice-not-required.mdx
This PR adds a new `snapshot_description` field to the block device configuration for the `amazon-ebsvolume` builder. If the companion field `snapshot_volume` is set for the block device, the value of `snapshot_description` will be included as the Description when creating the snapshot.
See [AWS Documentation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSnapshot.html#API_CreateSnapshot_RequestParameters) for the Description request parameter.
Closes #470
=> Enable setting a description for EBS Volume Snapshots

.web-docs/components/builder/chroot/README.md, .web-docs/components/builder/ebs/README.md, .web-docs/components/builder/ebssurrogate/README.md, .web-docs/components/builder/instance/README.md, builder/chroot/builder.go, builder/chroot/builder.hcl2spec.go, builder/common/ami_config.go, builder/common/step_enable_deprecation.go, builder/ebs/builder.go, builder/ebs/builder.hcl2spec.go, builder/ebssurrogate/builder.go, builder/ebssurrogate/builder.hcl2spec.go, builder/ebssurrogate/builder_acc_test.go, builder/instance/builder.go, builder/instance/builder.hcl2spec.go, docs-partials/builder/common/AMIConfig-not-required.mdx, docs-partials/builder/ebs/Config-not-required.mdx
Since the depreciation_time attribute implies being able to deprecate an AMI after a specific date, it should apply to any builder able to produce AMIs, that is everything but ebsvolume.
So this commit moves that to common, so all the builders (ebs, ebssurrogate, chroot and instance) are able to support it.
Closes #478
=> common: move deprecation_time to AMIConfig

builder/common/run_config.go, builder/common/run_config_test.go
The capacity reservation options (ID, ARN, or Preference) are all mutually exclusive, only one of the three should be set in a given configuration.
The code wasn't enforcing this, leading to cases in which conflicts could be specified in the configuration, and the call to start the instance would then fail during build instead of before it starts.
This commit adds some logic to ensure that only valid options are accepted, and some tests are added to make sure these options cannot conflict.
Closes #473
=> common: validate capacity reservation options

.web-docs/components/builder/chroot/README.md, .web-docs/components/builder/ebs/README.md, .web-docs/components/builder/ebssurrogate/README.md, .web-docs/components/builder/ebsvolume/README.md, .web-docs/components/builder/instance/README.md, builder/common/block_device.go, docs-partials/builder/common/BlockDevice-not-required.mdx
The `virtual_name` attribute for block devices did not have a clear documentation, which led to confusion for users of the plugin.
This commit enhances this to clarify these are expected to have a specific format, and are only for instance-based (ephemeral) volumes.
Closes #459
=> builder: improve documentation on virtual_name

.web-docs/components/builder/ebs/README.md, .web-docs/components/builder/ebssurrogate/README.md, .web-docs/components/builder/ebsvolume/README.md, .web-docs/components/builder/instance/README.md, builder/chroot/step_create_volume_test.go, builder/chroot/step_register_ami.go, builder/common/run_config.go, builder/common/step_modify_ebs_instance.go, builder/common/step_network_info.go, builder/common/step_run_source_instance.go, builder/common/step_run_spot_instance.go, builder/common/step_source_ami_info.go, builder/ebssurrogate/step_register_ami.go, builder/instance/step_register_ami.go, docs-partials/builder/common/RunConfig-not-required.mdx
Since most of those instances of confighelper were not necessary as there is not a config package, nor is there local name conflicts as well, we can remove those instaces, especially the one from Config as it caused the (fragile) typechecks from the SDK to not render it as a boolean in the web docs otherwise.
Related to https://github.com/hashicorp/packer-plugin-sdk/pull/244
=> builder: remove instances of confighelper.Trilean

.web-docs/components/builder/ebssurrogate/README.md, builder/ebssurrogate/builder.go, builder/ebssurrogate/builder.hcl2spec.go, builder/ebssurrogate/step_snapshot_volumes.go, builder/ebsvolume/step_snapshot_ebs_volumes.go, docs-partials/builder/ebssurrogate/Config-not-required.mdx
Similar to EBS volume, this PR extends the support of setting Snapshot description in EBS surrogate
=> feat: enable setting a snapshot description for EBS surrogate

.web-docs/components/builder/ebs/README.md, .web-docs/components/builder/ebssurrogate/README.md, .web-docs/components/builder/ebsvolume/README.md, .web-docs/components/builder/instance/README.md, builder/common/run_config.go, docs-partials/builder/common/RunConfig-not-required.mdx, docs/builders/ebs.mdx, docs/builders/ebssurrogate.mdx, docs/builders/ebsvolume.mdx, docs/builders/instance.mdx
The placement configuration options were statically written as part of the placement docs instead of included through the generated partials, so this commit adds a section for those, and references that from where they were initially injected.
Closes #507
=> docs: update placement configuration docs

.web-docs/components/builder/ebs/README.md, builder/ebs/builder_acc_test.go, builder/ebs/fast_launch_setup.go, builder/ebs/fast_launch_setup.hcl2spec.go, builder/ebs/step_enable_fast_launch.go, builder/ebs/step_prepare_fast_launch_template.go, docs-partials/builder/ebs/FastLaunchTemplateConfig-not-required.mdx
The fast-launch configuration allows setupping fast-launch for Windows virtual machines, either with a common configuration, or with a region-by-region configuration.
However if someone wants to only enable fast-launch on a subset of regions, there wasn't any way to express that, leading to either a waste of resources, or a need to manually cleanup the extra snapshots created.
Therefore this commit adds an extra trilean to the regional configuration for fast-launch, so it can be explicitly disabled on selected regions.
Closes: #506
=> Allow fast boot disable on region

.web-docs/components/builder/ebs/README.md, docs/builders/ebs.mdx
The sysprep commands currently in the documentation do not work anymore. That is because they are written for EC2Launch v1. V2 moved to new executables in a different location where previously v1 used scripts. v2 is the default for all windows AMIs now as far as i can tell.
The new addition to the docs I have confirmed work for 2022. However, I was not able to get a 2016 or 2019 server working with sysprep provisioners commands. I'm leaving them as is
=> Fix 2022 sysprep provisioner cmd

.web-docs/components/builder/ebs/README.md, .web-docs/components/builder/ebssurrogate/README.md, builder/ebs/builder.go, builder/ebs/builder.hcl2spec.go, builder/ebs/builder_acc_test.go, builder/ebs/step_create_ami.go, builder/ebs/test-fixtures/interpolated_run_tags.pkr.hcl, builder/ebs/test-fixtures/interpolated_skip_run_tags.pkr.hcl, builder/ebs/test-fixtures/interpolated_skip_run_tags_create_ami_tags.pkr.hcl, builder/ebssurrogate/builder.go, builder/ebssurrogate/builder.hcl2spec.go, builder/ebssurrogate/builder_acc_test.go, builder/ebssurrogate/step_create_ami.go, builder/ebssurrogate/test-fixtures/interpolated_ebs_surrogate_basic.pkr.hcl, builder/ebssurrogate/test-fixtures/interpolated_ebs_surrogate_basic_imdsv2.pkr.hcl, builder/ebssurrogate/test-fixtures/interpolated_ebs_surrogate_create_image.pkr.hcl, builder/ebssurrogate/test-fixtures/interpolated_ebs_surrogate_create_image_false.pkr.hcl, builder/ebssurrogate/test-fixtures/interpolated_ebs_surrogate_create_image_optional.pkr.hcl, builder/ebssurrogate/test-fixtures/interpolated_ebs_surrogate_private_key_file.pkr.hcl, builder/ebssurrogate/test-fixtures/interpolated_ebs_surrogate_with_deprecate_at.pkr.hcl, builder/ebssurrogate/test-fixtures/interpolated_skip_run_tags.pkr.hcl, docs-partials/builder/ebs/Config-not-required.mdx, docs-partials/builder/ebssurrogate/Config-not-required.mdx
Provide a way to users to allow them to skip the tags that are created to be attached to the AMI.
As of today we propagate the tags that are set in run_tags to the AMI. I propose on adding a new config
**_skip_ami_run_tags_** : Setting this config to True would make sure the tags set in run_tags are not propagated to the finished AMI instance.
Closes: https://github.com/hashicorp/packer-plugin-amazon/issues/361
=>  Skip attaching run tags to the finished AMI.

.web-docs/components/builder/ebs/README.md, docs/builders/ebs.mdx
This PR updates the firewall rule creation command to ensure it applies to all network profiles (Public, Private, and Domain) instead of being limited to the Public profile.
Issue: The old command implicitly applied the firewall rule only to the Public network profile. This could cause issues if a user changes their network profile to Private or Domain, as the rule would no longer be effective, potentially blocking traffic on port 5986.
This change ensures that port 5986 remains open regardless of the active network profile. It addresses potential issues where the rule would not be applied if the user's network profile switched from public to private, thereby preventing unintended connectivity problems. (i/o timeout issues)
=> fix(docs): correct firewall command for WinRM HTTPS setup

.web-docs/components/builder/ebs/README.md, .web-docs/components/builder/ebssurrogate/README.md, .web-docs/components/builder/ebsvolume/README.md, .web-docs/components/builder/instance/README.md, builder/common/run_config.go, builder/common/run_config_test.go, builder/common/step_run_spot_instance.go, builder/common/step_run_spot_instance_test.go, builder/ebs/builder.go, builder/ebs/builder.hcl2spec.go, builder/ebssurrogate/builder.go, builder/ebssurrogate/builder.hcl2spec.go, builder/ebsvolume/builder.go, builder/ebsvolume/builder.hcl2spec.go, builder/instance/builder.go, builder/instance/builder.hcl2spec.go, docs-partials/builder/common/RunConfig-not-required.mdx
Allow user to pass Spot Allocation Strategy into Fleet Request. 
Closes #427
=> feat: allow customizing spot allocation strategy

common/access_config.go, common/access_config_test.go
Fixes #563
The AMI datasource was failing to detect AWS credentials when using IMDS (Instance Metadata Service) after the migration from builder/common to common in commit 6aada6bc.
The issue was in common/access_config.go where the getBaseAwsConfig method incorrectly used SkipCredsValidation to control IMDS availability instead of SkipMetadataApiCheck.
This fix:
- Changes the IMDS control logic to use SkipMetadataApiCheck instead of SkipCredsValidation
- Ensures IMDS is enabled by default for credential resolution
- Only disables IMDS when skip_metadata_api_check is explicitly set to true
- Adds comprehensive tests to prevent regression
The fix restores the expected behavior where EC2 instances with IAM roles can use IMDS for credential resolution with the AMI datasource.
=> fix: IMDS credential detection in AMI datasource

go.mod, go.sum
updating oauth2 to v0.27 from v0.13
Security scanning is failing because of a vulnerability detected in oauth2 v0.13. Upgrading it v0.27
=> chore: updating oauth to v0.27

builder/ebs/builder_acc_test.go
Acceptance test workflow has been failing for the plugin. This PR is an effort to address that.
=> fixing the acceptance test EbsCopyRegionEncryptedBootWithDeprecation
